//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace WFC_CS.LowLevel {

class wfcPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="SWIGRegisterExceptionCallbacks_wfc")]
    public static extern void SWIGRegisterExceptionCallbacks_wfc(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_wfc")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_wfc(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_wfc(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_wfc(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="SWIGRegisterStringCallback_wfc")]
    public static extern void SWIGRegisterStringCallback_wfc(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_wfc(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static wfcPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Invert___")]
  public static extern int Invert(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_WillSwapAxes___")]
  public static extern bool WillSwapAxes(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_ToString___")]
  public static extern string ToString(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_IsReflection___")]
  public static extern bool IsReflection(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector2i_x_set___")]
  public static extern void Vector2i_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector2i_x_get___")]
  public static extern int Vector2i_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector2i_y_set___")]
  public static extern void Vector2i_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector2i_y_get___")]
  public static extern int Vector2i_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_Vector2i__SWIG_0___")]
  public static extern global::System.IntPtr new_Vector2i__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_Vector2i__SWIG_1___")]
  public static extern global::System.IntPtr new_Vector2i__SWIG_1(int jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector2i_LessX___")]
  public static extern global::System.IntPtr Vector2i_LessX(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector2i_MoreX___")]
  public static extern global::System.IntPtr Vector2i_MoreX(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector2i_LessY___")]
  public static extern global::System.IntPtr Vector2i_LessY(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector2i_MoreY___")]
  public static extern global::System.IntPtr Vector2i_MoreY(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector2i_Transform___")]
  public static extern global::System.IntPtr Vector2i_Transform(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector2i_GetHashcode___")]
  public static extern int Vector2i_GetHashcode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_delete_Vector2i___")]
  public static extern void delete_Vector2i(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Region2i_MinInclusive_set___")]
  public static extern void Region2i_MinInclusive_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Region2i_MinInclusive_get___")]
  public static extern global::System.IntPtr Region2i_MinInclusive_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Region2i_MaxExclusive_set___")]
  public static extern void Region2i_MaxExclusive_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Region2i_MaxExclusive_get___")]
  public static extern global::System.IntPtr Region2i_MaxExclusive_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_Region2i__SWIG_0___")]
  public static extern global::System.IntPtr new_Region2i__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_Region2i__SWIG_1___")]
  public static extern global::System.IntPtr new_Region2i__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Region2i_Contains___")]
  public static extern bool Region2i_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Region2i_GetSize___")]
  public static extern global::System.IntPtr Region2i_GetSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_delete_Region2i___")]
  public static extern void delete_Region2i(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector3i_Zero___")]
  public static extern global::System.IntPtr Vector3i_Zero();

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector3i_x_set___")]
  public static extern void Vector3i_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector3i_x_get___")]
  public static extern int Vector3i_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector3i_y_set___")]
  public static extern void Vector3i_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector3i_y_get___")]
  public static extern int Vector3i_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector3i_z_set___")]
  public static extern void Vector3i_z_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector3i_z_get___")]
  public static extern int Vector3i_z_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_Vector3i__SWIG_0___")]
  public static extern global::System.IntPtr new_Vector3i__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_Vector3i__SWIG_1___")]
  public static extern global::System.IntPtr new_Vector3i__SWIG_1(int jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector3i_LessX___")]
  public static extern global::System.IntPtr Vector3i_LessX(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector3i_MoreX___")]
  public static extern global::System.IntPtr Vector3i_MoreX(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector3i_LessY___")]
  public static extern global::System.IntPtr Vector3i_LessY(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector3i_MoreY___")]
  public static extern global::System.IntPtr Vector3i_MoreY(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector3i_LessZ___")]
  public static extern global::System.IntPtr Vector3i_LessZ(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector3i_MoreZ___")]
  public static extern global::System.IntPtr Vector3i_MoreZ(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Vector3i_GetHashcode___")]
  public static extern int Vector3i_GetHashcode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_delete_Vector3i___")]
  public static extern void delete_Vector3i(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Region3i_MinInclusive_set___")]
  public static extern void Region3i_MinInclusive_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Region3i_MinInclusive_get___")]
  public static extern global::System.IntPtr Region3i_MinInclusive_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Region3i_MaxExclusive_set___")]
  public static extern void Region3i_MaxExclusive_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Region3i_MaxExclusive_get___")]
  public static extern global::System.IntPtr Region3i_MaxExclusive_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_Region3i__SWIG_0___")]
  public static extern global::System.IntPtr new_Region3i__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_Region3i__SWIG_1___")]
  public static extern global::System.IntPtr new_Region3i__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Region3i_Contains___")]
  public static extern bool Region3i_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Region3i_GetSize___")]
  public static extern global::System.IntPtr Region3i_GetSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_delete_Region3i___")]
  public static extern void delete_Region3i(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_IsFirstMin___")]
  public static extern bool IsFirstMin(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_IsSecondMin___")]
  public static extern bool IsSecondMin(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_MakeFacePoint___")]
  public static extern int MakeFacePoint(bool jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_IsMin___")]
  public static extern bool IsMin(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_IsMax___")]
  public static extern bool IsMax(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_GetAxisIndex___")]
  public static extern byte GetAxisIndex(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_GetOpposite___")]
  public static extern int GetOpposite(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_FacePermutation_Points_set___")]
  public static extern void FacePermutation_Points_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_FacePermutation_Points_get___")]
  public static extern global::System.IntPtr FacePermutation_Points_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_FacePermutation_Side_set___")]
  public static extern void FacePermutation_Side_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_FacePermutation_Side_get___")]
  public static extern int FacePermutation_Side_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_FacePermutation___")]
  public static extern global::System.IntPtr new_FacePermutation();

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_delete_FacePermutation___")]
  public static extern void delete_FacePermutation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_CubePermutation_Faces_set___")]
  public static extern void CubePermutation_Faces_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_CubePermutation_Faces_get___")]
  public static extern global::System.IntPtr CubePermutation_Faces_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_CubePermutation_GetFace___")]
  public static extern byte CubePermutation_GetFace(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_CubePermutation___")]
  public static extern global::System.IntPtr new_CubePermutation();

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_delete_CubePermutation___")]
  public static extern void delete_CubePermutation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Transform3D_Invert_set___")]
  public static extern void Transform3D_Invert_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Transform3D_Invert_get___")]
  public static extern bool Transform3D_Invert_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Transform3D_Rot_set___")]
  public static extern void Transform3D_Rot_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Transform3D_Rot_get___")]
  public static extern int Transform3D_Rot_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Transform3D_ApplyToPos__SWIG_0___")]
  public static extern global::System.IntPtr Transform3D_ApplyToPos__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Transform3D_ApplyToPos__SWIG_1___")]
  public static extern global::System.IntPtr Transform3D_ApplyToPos__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Transform3D_ApplyToSide___")]
  public static extern int Transform3D_ApplyToSide(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Transform3D_ApplyToFace___")]
  public static extern global::System.IntPtr Transform3D_ApplyToFace(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_Transform3D_ApplyToCube___")]
  public static extern global::System.IntPtr Transform3D_ApplyToCube(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_Transform3D___")]
  public static extern global::System.IntPtr new_Transform3D();

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_delete_Transform3D___")]
  public static extern void delete_Transform3D(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_eFlagsList__SWIG_0___")]
  public static extern global::System.IntPtr new_eFlagsList__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_eFlagsList__SWIG_1___")]
  public static extern global::System.IntPtr new_eFlagsList__SWIG_1(ushort jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_eFlagsList__SWIG_2___")]
  public static extern global::System.IntPtr new_eFlagsList__SWIG_2(ushort jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_eFlagsList__SWIG_3___")]
  public static extern global::System.IntPtr new_eFlagsList__SWIG_3(ushort jarg1, ushort jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_eFlagsList__SWIG_4___")]
  public static extern global::System.IntPtr new_eFlagsList__SWIG_4(ushort jarg1, ushort jarg2, ushort jarg3, ushort jarg4);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlagsList_GetSize___")]
  public static extern uint eFlagsList_GetSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlagsList_GetData__SWIG_0___")]
  public static extern global::System.IntPtr eFlagsList_GetData__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlagsList_Resize___")]
  public static extern void eFlagsList_Resize(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlagsList_Reserve___")]
  public static extern void eFlagsList_Reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlagsList_PushBack___")]
  public static extern void eFlagsList_PushBack(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlagsList_PushFront___")]
  public static extern void eFlagsList_PushFront(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlagsList_PopBack___")]
  public static extern ushort eFlagsList_PopBack(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlagsList_PopFront___")]
  public static extern ushort eFlagsList_PopFront(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlagsList_RemoveAt___")]
  public static extern void eFlagsList_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlagsList_Insert__SWIG_0___")]
  public static extern void eFlagsList_Insert__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, ushort jarg3);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlagsList_Insert__SWIG_1___")]
  public static extern void eFlagsList_Insert__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlagsList_Clear___")]
  public static extern void eFlagsList_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlagsList_GetBack__SWIG_0___")]
  public static extern global::System.IntPtr eFlagsList_GetBack__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_delete_eFlagsList___")]
  public static extern void delete_eFlagsList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlags_ToMask___")]
  public static extern int eFlags_ToMask(ushort jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlags_All___")]
  public static extern global::System.IntPtr eFlags_All();

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlags_BitMask_set___")]
  public static extern void eFlags_BitMask_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlags_BitMask_get___")]
  public static extern int eFlags_BitMask_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_eFlags__SWIG_0___")]
  public static extern global::System.IntPtr new_eFlags__SWIG_0(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_eFlags__SWIG_1___")]
  public static extern global::System.IntPtr new_eFlags__SWIG_1();

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_eFlags__SWIG_2___")]
  public static extern global::System.IntPtr new_eFlags__SWIG_2(ushort jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlags_Contains___")]
  public static extern bool eFlags_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_eFlags_Enumerate___")]
  public static extern void eFlags_Enumerate(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_delete_eFlags___")]
  public static extern void delete_eFlags(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_dictIntDouble_GetSize___")]
  public static extern uint dictIntDouble_GetSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_dictIntDouble_Reserve___")]
  public static extern void dictIntDouble_Reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_dictIntDouble_Contains___")]
  public static extern bool dictIntDouble_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_dictIntDouble_Clear___")]
  public static extern void dictIntDouble_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_dictIntDouble_TryGet__SWIG_0___")]
  public static extern global::System.IntPtr dictIntDouble_TryGet__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_dictIntDouble_Get__SWIG_0___")]
  public static extern double dictIntDouble_Get__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, double jarg3);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_dictIntDouble___")]
  public static extern global::System.IntPtr new_dictIntDouble();

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_delete_dictIntDouble___")]
  public static extern void delete_dictIntDouble(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_setOfUInts_GetSize___")]
  public static extern uint setOfUInts_GetSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_setOfUInts_Reserve___")]
  public static extern void setOfUInts_Reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_setOfUInts_Add__SWIG_0___")]
  public static extern bool setOfUInts_Add__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_setOfUInts_Add__SWIG_1___")]
  public static extern void setOfUInts_Add__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_setOfUInts_Erase__SWIG_0___")]
  public static extern bool setOfUInts_Erase__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_setOfUInts_Erase__SWIG_1___")]
  public static extern void setOfUInts_Erase__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_setOfUInts_Contains___")]
  public static extern bool setOfUInts_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_setOfUInts_Clear___")]
  public static extern void setOfUInts_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_setOfUInts___")]
  public static extern global::System.IntPtr new_setOfUInts();

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_delete_setOfUInts___")]
  public static extern void delete_setOfUInts(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_algoState_HasValue_set___")]
  public static extern void algoState_HasValue_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_algoState_HasValue_get___")]
  public static extern bool algoState_HasValue_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_algoState_Value_set___")]
  public static extern void algoState_Value_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_algoState_Value_get___")]
  public static extern bool algoState_Value_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_algoState__SWIG_0___")]
  public static extern global::System.IntPtr new_algoState__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_algoState__SWIG_1___")]
  public static extern global::System.IntPtr new_algoState__SWIG_1(bool jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_new_algoState__SWIG_2___")]
  public static extern global::System.IntPtr new_algoState__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("wfc", EntryPoint="CSharp_WFC_CSfLowLevel_delete_algoState___")]
  public static extern void delete_algoState(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
